const $=s=>document.querySelector(s);
const state={key:sessionStorage.getItem("chefsapiens.admin.session")||"",all:[],filtered:[]};
const msg=(id,text,type="")=>{const el=$(id);el.textContent=text;el.className=`status ${type}`.trim()};
const fmtDate=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(d)};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const score=row=>{let n=0;const t=(row.timeline||"").toLowerCase(),v=(row.volume||"").toLowerCase(),u=(row.useCase||"").toLowerCase();if(t.includes("7 dias"))n+=4;else if(t.includes("30 dias"))n+=3;else if(t.includes("90 dias"))n+=1;if(v.includes("acima")||v.includes("milhão"))n+=4;else if(v.includes("150 mil"))n+=3;else if(v.includes("20 mil a"))n+=2;else n+=1;if((row.source||"")==="sales")n+=2;if(u.includes("growth")||u.includes("scale")||u.includes("enterprise"))n+=2;return n};
const priority=row=>{const n=score(row);return n>=8?["Alta","p-high"]:n>=5?["Média","p-medium"]:["Baixa","p-low"]};
async function load(){msg("#table-status","Atualizando registros…");const r=await fetch("/internal/leads",{headers:{"x-admin-key":state.key}});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(j?.error?.message||`Falha HTTP ${r.status}`),{status:r.status});state.all=Array.isArray(j?.data?.leads)?j.data.leads:[];render();msg("#table-status",`${state.all.length} registro(s) carregado(s).`,"success")}
function render(){
 const q=$("#q").value.trim().toLowerCase(),src=$("#source").value,st=$("#status").value,tl=$("#timeline").value;
 state.filtered=state.all.filter(r=>{const hay=[r.company,r.contactName,r.email,r.useCase].join(" ").toLowerCase();return(!q||hay.includes(q))&&(!src||r.source===src)&&(!st||r.status===st)&&(!tl||r.timeline===tl)}).sort((a,b)=>score(b)-score(a)||new Date(b.createdAt)-new Date(a.createdAt));
 $("#m-total").textContent=state.all.length;$("#m-new").textContent=state.all.filter(r=>r.status==="new").length;$("#m-trial").textContent=state.all.filter(r=>r.source==="trial").length;$("#m-sales").textContent=state.all.filter(r=>r.source==="sales").length;
 $("#rows").innerHTML=state.filtered.map(r=>{const [p,pc]=priority(r),srcCls=r.source==="trial"?"source-trial":"source-sales";return `<tr><td><span class="priority ${pc}">${p}</span></td><td>${esc(fmtDate(r.createdAt))}</td><td class="source ${srcCls}">${esc(r.source||"—")}</td><td><strong>${esc(r.contactName||"—")}</strong><br><span class="muted">${esc(r.email||"—")}</span></td><td>${esc(r.company||"—")}</td><td>${esc(r.volume||"—")}</td><td>${esc(r.timeline||"—")}</td><td class="usecase">${esc(r.useCase||"—")}</td></tr>`}).join("");
 $("#empty").hidden=state.filtered.length>0
}
function connected(on){$("#workspace").hidden=!on;$("#auth-state").textContent=on?"Conectado":"Desconectado";$("#auth-state").className=`pill ${on?"":"neutral"}`;if(on)$("#admin-key").value=""}
$("#auth-form").addEventListener("submit",async e=>{e.preventDefault();state.key=$("#admin-key").value.trim();if(!state.key)return;try{await load();sessionStorage.setItem("chefsapiens.admin.session",state.key);connected(true);msg("#auth-status","Acesso administrativo conectado.","success")}catch(err){state.key="";sessionStorage.removeItem("chefsapiens.admin.session");connected(false);msg("#auth-status",err.status===401?"Chave administrativa inválida.":err.message,"error")}});
["#q","#source","#status","#timeline"].forEach(id=>$(id).addEventListener("input",render));
$("#refresh").addEventListener("click",()=>load().catch(err=>msg("#table-status",err.message,"error")));
$("#disconnect").addEventListener("click",()=>{state.key="";state.all=[];state.filtered=[];sessionStorage.removeItem("chefsapiens.admin.session");connected(false);msg("#auth-status","Chave removida desta sessão.","success")});
$("#export").addEventListener("click",()=>{const cols=["prioridade","data","origem","status","contato","email","empresa","volume","prazo","caso_de_uso","consentimento"];const rows=state.filtered.map(r=>[priority(r)[0],r.createdAt,r.source,r.status,r.contactName,r.email,r.company,r.volume,r.timeline,r.useCase,r.consentAt]);const csv=[cols,...rows].map(row=>row.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\r\n");const blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`chefsapiens-leads-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
if(state.key){load().then(()=>{connected(true);msg("#auth-status","Sessão administrativa restaurada.","success")}).catch(()=>{state.key="";sessionStorage.removeItem("chefsapiens.admin.session");connected(false)})}else connected(false);
