const $=(s)=>document.querySelector(s);
const state={key:sessionStorage.getItem("chefsapiens.session.key")||"",called:sessionStorage.getItem("chefsapiens.session.called")==="1"};
const fmt=(n)=>new Intl.NumberFormat("pt-BR").format(Number(n||0));
function message(id,text,type=""){const el=$(id);el.textContent=text;el.className=`status ${type}`.trim()}
function maskDate(value){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium"}).format(d)}
function setConnected(on){$("#workspace").hidden=!on;$("#connection-state").textContent=on?"Conectado":"Desconectado";$("#connection-state").className=`pill ${on?"":"neutral"}`;if(on)$("#api-key").value=""}
async function api(path,options={}){const headers=new Headers(options.headers||{});headers.set("x-api-key",state.key);const res=await fetch(path,{...options,headers});let body=null;try{body=await res.json()}catch{}if(!res.ok){const msg=body?.error?.message||`Falha HTTP ${res.status}`;const e=new Error(msg);e.status=res.status;throw e}return{res,body}}
async function loadUsage(){const {body}=await api("/v1/account/usage");const d=body.data;$("#plan-value").textContent=d.plan||"trial";$("#used-value").textContent=fmt(d.used);$("#quota-value").textContent=fmt(d.quota);$("#remaining-value").textContent=`${fmt(d.remaining)} restantes`;$("#expiry-value").textContent=maskDate(d.expiresAt);if(d.expiresAt){const days=Math.max(0,Math.ceil((new Date(d.expiresAt)-Date.now())/86400000));$("#days-value").textContent=`${days} dia${days===1?"":"s"} restantes`}else{$("#days-value").textContent="Sem expiração informada"}setConnected(true);message("#connect-status","Chave conectada com segurança.","success")}
async function connect(key){state.key=key.trim();if(!state.key)throw new Error("Informe uma API key.");await loadUsage();sessionStorage.setItem("chefsapiens.session.key",state.key)}
$("#connect-form").addEventListener("submit",async(e)=>{e.preventDefault();message("#connect-status","Validando chave…");try{await connect($("#api-key").value)}catch(err){state.key="";sessionStorage.removeItem("chefsapiens.session.key");setConnected(false);message("#connect-status",err.status===401?"Chave inválida ou expirada.":err.message,"error")}});
$("#refresh-usage").addEventListener("click",async()=>{try{await loadUsage();message("#test-status","Consumo atualizado.","success")}catch(err){message("#test-status",err.message,"error")}});
$("#run-test").addEventListener("click",async()=>{message("#test-status","Executando chamada…");try{const {res,body}=await api("/v1/recipes");const sample={status:res.status,quota:{used:res.headers.get("x-quota-used"),remaining:res.headers.get("x-quota-remaining")},data:Array.isArray(body.data)?body.data.slice(0,2):body.data};$("#test-output code").textContent=JSON.stringify(sample,null,2);state.called=true;sessionStorage.setItem("chefsapiens.session.called","1");$("#step-call").classList.add("done");$("#progress-pill").textContent="2 de 4";await loadUsage();message("#test-status","Primeira chamada concluída.","success")}catch(err){message("#test-status",err.message,"error")}});
$("#copy-curl").addEventListener("click",async()=>{const text=`curl https://culinaria-rc3-hml.homosapiens.id/v1/recipes \\\n  -H "x-api-key: SUA_CHAVE_NO_BACKEND"`;try{await navigator.clipboard.writeText(text);message("#test-status","Exemplo copiado sem incluir sua chave.","success")}catch{message("#test-status","Não foi possível copiar automaticamente.","error")}});
$("#disconnect").addEventListener("click",()=>{state.key="";state.called=false;sessionStorage.removeItem("chefsapiens.session.key");sessionStorage.removeItem("chefsapiens.session.called");setConnected(false);$("#test-output code").textContent="O resultado aparecerá aqui.";$("#step-call").classList.remove("done");$("#progress-pill").textContent="1 de 4";message("#connect-status","Chave removida desta sessão.","success")});
if(state.called){$("#step-call").classList.add("done");$("#progress-pill").textContent="2 de 4"}
if(state.key){loadUsage().catch(()=>{state.key="";sessionStorage.removeItem("chefsapiens.session.key");setConnected(false);message("#connect-status","A sessão anterior expirou. Conecte a chave novamente.","error")})}else setConnected(false);